---
stages:
  - syntax
  - unit
  - acceptance
  - release

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
  - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop-Ruby 2.4.4-Puppet ~> 5.5:
  stage: syntax
  image: ruby:2.4.4
  script:
    - bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 5.5'

parallel_spec-Ruby 2.4.4-Puppet ~> 5.5:
  stage: unit
  image: ruby:2.4.4
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 5.5'

acceptance with puppet5 ubuntu1604:
  stage: acceptance
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_debug: 'true '
    BEAKER_setfile: 'host.yml'
    RBENV_VERSION: '2.5.1'
  script:
    - beaker-hostgenerator ubuntu1604-64{hypervisor=docker} > host.yml
    - bundle exec rake beaker
  tags:
    - puppet-tests

acceptance with puppet5 debian8:
  stage: acceptance
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_debug: 'true '
    BEAKER_setfile: 'host.yml'
    RBENV_VERSION: '2.5.1'
  script:
    - beaker-hostgenerator debian8-64{hypervisor=docker} > host.yml
    - bundle exec rake beaker
  tags:
    - puppet-tests

acceptance with puppet5 debian9:
  stage: acceptance
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_debug: 'true '
    BEAKER_setfile: 'host.yml'
    RBENV_VERSION: '2.5.1'
  script:
    - beaker-hostgenerator debian9-64{hypervisor=docker} > host.yml
    - bundle exec rake beaker
  tags:
    - puppet-tests

acceptance with puppet5 centos7:
  stage: acceptance
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_debug: 'true '
    BEAKER_setfile: 'host.yml'
    RBENV_VERSION: '2.5.1'
  script:
    - beaker-hostgenerator centos7-64{hypervisor=docker} > host.yml
    - bundle exec rake beaker
  tags:
    - puppet-tests

acceptance with puppet6 ubuntu1604:
  stage: acceptance
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet6'
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_debug: 'true '
    BEAKER_setfile: 'host.yml'
    RBENV_VERSION: '2.5.1'
  script:
    - beaker-hostgenerator ubuntu1604-64{hypervisor=docker} > host.yml
    - bundle exec rake beaker
  tags:
    - puppet-tests

acceptance with puppet6 debian8:
  stage: acceptance
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet6'
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_debug: 'true '
    BEAKER_setfile: 'host.yml'
    RBENV_VERSION: '2.5.1'
  script:
    - beaker-hostgenerator debian8-64{hypervisor=docker} > host.yml
    - bundle exec rake beaker
  tags:
    - puppet-tests

acceptance with puppet6 debian9:
  stage: acceptance
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet6'
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_debug: 'true '
    BEAKER_setfile: 'host.yml'
    RBENV_VERSION: '2.5.1'
  script:
    - beaker-hostgenerator debian9-64{hypervisor=docker} > host.yml
    - bundle exec rake beaker
  tags:
    - puppet-tests

acceptance with puppet6 centos7:
  stage: acceptance
  variables:
    BEAKER_PUPPET_COLLECTION: 'puppet6'
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_debug: 'true '
    BEAKER_setfile: 'host.yml'
    RBENV_VERSION: '2.5.1'
  script:
    - beaker-hostgenerator centos7-64{hypervisor=docker} > host.yml
    - bundle exec rake beaker
  tags:
    - puppet-tests

module release:
  stage: release
  variables:
    RBENV_VERSION: '2.5.1'
  script: 
    - pdk build
  tags:
    - puppet-tests
  when: manual
  allow_failure: false
  only:
    - master
  artifacts:
    paths:
      - pkg/
    expire_in: 6 weeks

