type Wordpress::Settings = Hash[
  String,
  Hash[
    Enum[
      'ensure',
      'wproot',
      'owner',
      'locale',
      'dbhost',
      'dbname',
      'dbuser',
      'dbpasswd',
      'dbprefix',
      'wpselfupdate',
      'wptitle',
      'wpadminuser',
      'wpadminpasswd',
      'wpadminemail',
      'wpresources'
    ],
    Variant[
      String,
      Hash[
        Enum['plugin','theme'],
        Array[
          Hash[
            Enum['name','ensure'],
            String
            ]
          ]
        ]
      ]
    ]
  ]
